name: "Terraform Plan and Apply Action"

on:
  workflow_call:

# permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  pull-requests: write

# Define the script as a variable
env:
  HELLO_WORLD_SCRIPT: |
    github.rest.issues.createComment({
      issue_number: context.issue.number,
      owner: context.repo.owner,
      repo: context.repo.repo,
      body: 'Hello, world!'
    })


jobs:
  comment:
    runs-on: ubuntu-20.04
    steps:
      - name: Hello World
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: ${{ env.HELLO_WORLD_SCRIPT }}
