name: "Terraform Plan and Apply Action"

on:
  workflow_call:
    inputs:
      is_gov_cloud:
        description: "Indicates whether the AWS GovCloud should be used."
        type: boolean
        required: false
        default: false
      aws_region:
        type: string
        description: "AWS region."
        required: true
        default: "us-east-1"
      role_to_assume:
        type: string
        description: "ARN of the AWS IAM role to assume."
        required: true

# Define the script as a variable
env:
  HELLO_WORLD_SCRIPT: |
    github.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: context.issue.number,
      body: 'Hello, World'
    });


jobs:
  comment:
    runs-on: ubuntu-20.04
    steps:
      - name: Hello World
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: ${{ env.HELLO_WORLD_SCRIPT }}
