name: "Terraform Plan and Apply Action"

on:
  workflow_call:
    inputs:
      is_gov_cloud:
        description: "Indicates whether the AWS GovCloud should be used."
        type: boolean
        required: false
        default: false
      aws_region:
        type: string
        description: "AWS region."
        required: true
        default: "us-east-1"
      role_to_assume:
        type: string
        description: "ARN of the AWS IAM role to assume."
        required: true

jobs:
  lint:
    name: Pre Checks
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Run terraform fmt check
        run: terraform fmt -check -diff -recursive

      - name: Run terraform validate check
        run: terraform validate -no-color

  plan:
    runs-on: ubuntu-20.04
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        path:
          - dev
          - prod

    steps:
      - name: Comment the Plan
        uses: actions/github-script@v6
        if: ${{ github.event_name == 'pull_request' }}
        env:
          ACTOR: "${{ github.actor }}"
          ENV: "${{ matrix.path }}"
          EVENT_NAME: "${{ github.event_name }}"
          PLAN_OUTCOME: "${{ steps.plan.outcome }}"
          WORKFLOW: "${{ github.workflow }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./.github/scripts/tf-plan-commenter.js');
            await script({github, context, process});
